// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qihfppphvisdaxbhlbjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpaGZwcHBodmlzZGF4YmhsYmpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczNzQyMDMsImV4cCI6MjA1Mjk1MDIwM30.WEJg68wZmISa0yiR8KUWWSowdwG_fawyfB5ObG7c3jY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);